### ISSUE TITLE
Cannot find module 'bluebird'

### ISSUE THREAD

**Issue by zfarrell** [fivepapertigers/serverless-plugin-pubsub#9]
Hi there, I just tried installing this plugin. Upon starting up `sls offline` i receive this error:
```
  Serverless plugin "serverless-plugin-pubsub" initialization errored: Cannot find module 'bluebird'
```

I don't see a dependency for `bluebird` within `package.json`, yet `index.js` uses it. 

For now, i'm able to get around this by installing bluebird within my project: `npm install --save-dev bluebird`. 

Let me know if I'm doing something wrong, or if this is a bug. Thanks!

**Comment by fivepapertigers** [comment]
@zfarrell, `bluebird` is a dependency of the `serverless` package, which is why it usually resolves correctly. But I'll make it an explicit install.

And apologies for the delay in response - this one must have slipped by me.
